config/routes.rb
Keittokirja::Application.routes.draw do
  get "ratings/create"
  get "comments/create"
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  get "users/new"
  get "users/create"
  get "users/show"
  get "recipes/index"
  get "recipes/show"
  get "recipes/new"
  get "recipes/create"
  get "recipes/destroy"
	
	resources :comments
	resources :users
	resources :recipes
	resources :sessions
	resources :ratings
	root to: 'recipes#index'

  

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base

	has_many :comments
	has_many :ratings
	belongs_to :user
	belongs_to :recipe
	
	has_attached_file :photo, :styles => { :small => "100x100>", :normal => "600x600>" }
	validates_presence_of :name, :directions, :user_id
	validates_attachment_size :photo, :less_than => 5.megabytes
	validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']

	def self.search(search)
		if search
			Recipe.where("lower(name) like ? or ingredients like ?", "%#{search.downcase}%","%#{search}%")
		else
			Recipe.all
		end
	end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

#metodi toimii sekä etusivuna, joka näyttää kaikki reseptit, että toteuttaa hakutoiminnallisuuden.
#jos parametrinä ei ole annettu hakusanoja, annetaan näkymään kaikki reseptit, jos on, annetaan
#vain kyseisen hakusanan sisältävät reseptit 
  def index
		@recipes = Recipe.search(params[:search])
  end

#Näytettävästä reseptistä ohjataan näkymään itse resepti sekä siihen 
#kommentit.
  def show
		@recipe = Recipe.find(params[:id])
		@comments = Comment.where('recipe_id = '+@recipe.id.to_s)
  end

  def new
  end

#metodia kutsutaan kun käyttäjä lähettää uuden reseptin lisättäväksi.
#resepti tallennetaan tietokantaan ja käyttäjä ohjataan reseptin sivulle.
  def create
		@recipe = Recipe.new
		@recipe.name = params[:name]
		@recipe.description = params[:description]
		@recipe.ingredients = params[:ingredients]
		@recipe.directions = params[:directions]
		@recipe.photo = params[:photo]
		@recipe.user_id = session[:user_id]
		if @recipe.save
			redirect_to root_path, :notice => "Resepti tallennettu!"
		else
			flash.alert = "Reseptissä puutteita"
			render 'new'
		end
  end
	
	def edit
		@recipe = Recipe.find(params[:id])
	end

	def update
		
		recipe = Recipe.find(params[:id])
		if current_user
			if current_user.id != recipe.user_id
				redirect_to recipe_path(recipe.id)
				return
			end
		else
			redirect_to recipe_path(recipe.id)
			return
		end

		recipe.name = params[:recipe][:name]
		recipe.description = params[:recipe][:description]
		recipe.ingredients = params[:recipe][:ingredients]
		recipe.directions = params[:recipe][:directions]
		if params[:recipe][:photo]
			recipe.photo = params[:recipe][:photo]
		end
		if recipe.save
			redirect_to recipe_path(recipe.id), :notice => "Resepti tallennettu"
		else
			flash.alert = "Reseptissä puutteita"
			redirect_to edit_recipe_path(recipe.id)
		end		
	end		

  def destroy
		recipe = Recipe.find(params[:id])
		recipe.delete
		redirect_to root_path
		
  end
	
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/edit.html.erb
<h1> Muokkaa reseptiä </h1>
	<div class="form">
		<%= form_tag(recipe_path,:multipart => true, method: 'patch') do %>
			<%= label_tag(:name, "Reseptin nimi") %> </br>
			<%= text_field(:recipe, :name) %> </br>
			<%= label_tag(:description, "Lyhyt kuvaus reseptistäsi") %> </br>
			<%= text_area(:recipe, :description, :size => "40x5") %> </br>
			<%= label_tag(:ingredients, "Ainesosat (erottele rivinvaihdoin)") %> </br>
			<%= text_area(:recipe, :ingredients, :size => "40x20") %> </br>
			<%= label_tag(:directions, "Valmistusohje") %>	</br>
			<%= text_area(:recipe, :directions, :size => "40x20") %> </br>
			<%= label_tag(:photo, "Kuva") %> </br>
			<%= file_field(:recipe, :photo) %> </br> 
			<%= hidden_field(:id, @recipe.id) %>
			<%= submit_tag("Lähetä") %> </br>
		<% end %>
	</div>

app/views/recipes/index.html.erb
<%= stylesheet_link_tag "recipes", media: "all", "data-turbolinks-track" => true %>
<% @recipes.each do |recipe| %>
	<div class="preview">
		<div class="small_image">
			<%= image_tag recipe.photo.url(:small) %>
		</div>
		<div class="preview_text">
			<h2> <%= link_to(recipe.name, "recipes/"+recipe.id.to_s) %> </h2>
			<p> <%= recipe.description %> </p>
		</div>
		<div class="footer">
			<div class="creator">
				Kirjoittanut: <%= find_user_by_recipe(recipe).nick %> </div>
			<div> <%= number_of_comments(recipe) %> kommenttia </div>
			<div> Käyttäjien arvio: <%= calculate_rating(recipe) %>/5 </div>
		</div>
	</div>
<% end %>

app/views/recipes/new.html.erb
<h1>Lisää uusi resepti</h1>
	<div class="form">
		<%= form_tag(recipes_path,:multipart => true) do %>
			<%= label_tag(:name, "Reseptin nimi") %> </br>
			<%= text_field_tag(:name) %> </br>
			<%= label_tag(:description, "Lyhyt kuvaus reseptistäsi") %> </br>
			<%= text_area_tag(:description, nil, :size => "40x5") %> </br>
			<%= label_tag(:ingredients, "Ainesosat (erottele rivinvaihdoin)") %> </br>
			<%= text_area_tag(:ingredients, nil, :size => "40x20") %> </br>
			<%= label_tag(:directions, "Valmistusohje") %>	</br>
			<%= text_area_tag(:directions, nil, :size => "40x20") %> </br>
			<%= label_tag(:photo, "Kuva") %> </br>
			<%= file_field_tag(:photo) %> </br> 
			<%= submit_tag("Lähetä") %> </br>
		<% end %>
	</div>

app/views/recipes/show.html.erb
<%= stylesheet_link_tag "recipes",media: "all", "data-turbolinks-track" => true %>
<h1> <%= @recipe.name %> </h1>
<p> kirjoittanut: <%= find_user_by_recipe(@recipe).nick %>
<% if owner_of_recipe(@recipe) %>
	<%= link_to "Muokkaa reseptiä", edit_recipe_path(@recipe.id)  %>
	<%= link_to "Poista resepti", recipe_path(@recipe.id), method: 'delete' %>
<% end %>
	 </p>
<%= image_tag @recipe.photo.url(:normal) %>
<% if current_user %>
<%= form_tag(ratings_path)  do %>
	<%= label_tag(:rating_1, "1") %>
	<%= radio_button_tag(:rating, "1") %>
	<%= label_tag(:rating_2, "2") %>
	<%= radio_button_tag(:rating, "2") %>
	<%= label_tag(:rating_3, "3") %>
	<%= radio_button_tag(:rating, "3") %>
	<%= label_tag(:rating_4, "4") %>
	<%= radio_button_tag(:rating, "4") %>
	<%= label_tag(:rating_5, "5") %>
	<%= radio_button_tag(:rating, "5") %>
	<%= submit_tag("tallenna arvio") %>
	<%= hidden_field_tag(:recipe_id, @recipe.id) %>
	<% end %>
<% end %>
<div class="textbox" id="left">
	<p>
		<%= create_line_breaks(@recipe.ingredients) %>
	</p>
</div>
<div class="textbox" id="right">
	<p>
		<%= create_line_breaks( @recipe.directions) %>
	</p>
</div>
<!-- näkymätön palkki sivun alareunassa, joka saa taustavärin jatkumaan elementtien loppuun asti. jostain syystä ei toiminut ilman tätä -->
<div class="special-footer">  </div>
<h2> Kommentit: </h2>
<% if @comments.size == 0 %>
	<p> ei kommentteja </p>
<% end %> 
<% @comments.each do |comment| %>
	<div class="comment">
		<p><%= comment.content %></p></br>
		<p> kirjoittanut: <%= find_user_by_comment(comment).nick %>
		<% if owner_of_comment(comment) %>
		<%= link_to "Poista kommentti", comment_path(comment.id), method: 'delete' %> </p> 
		<% end %>

	</div>
	<% end %>
	<% if session[:user_id] %>
<h1> Kirjoita kommentti </h1>
	<div class="form">
		<%= form_tag(comments_path) do %>
			<%= label_tag(:comment, "Kommentti:") %> </br>
			<%= text_area_tag(:comment) %> </br>
			<%= hidden_field_tag :recipe_id, @recipe.id  %>
			<%= submit_tag("Lähetä") %> </br>
	<% end %>
	</div>
	<% end %>