config/routes.rb
Keittokirja::Application.routes.draw do
  get "ratings/create"
  get "comments/create"
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  get "users/new"
  get "users/create"
  get "users/show"
  get "recipes/index"
  get "recipes/show"
  get "recipes/new"
  get "recipes/create"
  get "recipes/destroy"
	
	resources :comments
	resources :users
	resources :recipes
	resources :sessions
	resources :ratings
	root to: 'recipes#index'

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Keittokirja</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="content">
<div id="banner">
	<h1>	Keittokirja </p>
</div>
<ul id="navbar">
	<li> <%= form_tag(recipes_path,:method => :get) do %>
		<%= text_field_tag(:search) %>
		<%= submit_tag("hae reseptiä") %>
		<% end %>
	</li>
	<li> <%= link_to("etusivu", root_path) %> </li>
	<% if current_user %>
		<li> <%= link_to("kirjaudu ulos", sessions_destroy_path) %> </li>
		<li> <%= link_to("luo uusi resepti", recipes_new_path) %> </li>
	<% else %>
	<li> <%= link_to("kirjaudu sisään", sessions_new_path) %> </li>
	<li> <%= link_to("luo tunnus", users_new_path) %> </li>
	<% end %>
</ul></br>
<% if flash[:alert] %>
	<p class="alert"> <%= flash.alert %> </p> </br>
<% end %>
<% if flash[:notice] %>
	<p class="notice"> <%= flash.notice %> </p> 
<% end %>
</br></br>
<%= yield %>
</br>
</div>
</body>
</html>